### ISSUE TITLE
How to obtain the reconstructed image for inference and masked

### ISSUE THREAD

**Issue by hzxie99** [wgcban/adamae#3]
Hello, I very much agree with your work. I would like to know how to obtain the schematic diagram of the reconstructed image and the mask image during the experiment. Because I'm just getting started. I really appreciate it if you can help me with this question.

**Comment by wgcban** [comment]
@hzxie99 Thanks for your interest!.

I wrote a python notebook (which I cannot locate now, but similar to one used in image MAEs https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb) which 
1. first saves the predicted image and mask into numpy array
2. then visualize each frame in the video by re-arranging and re-normalizing and then saving it as png file

I will try to find my script and post it here. But, I would say it is a modification on top of the above python notebook file.

**Comment by hzxie99** [comment]
Thank you very much. The pictures in the paper are very beautiful. Thank you!!

**Comment by hzxie99** [comment]
> @hzxie99 Thanks for your interest!.
> 
> I wrote a python notebook (which I cannot locate now, but similar to one used in image MAEs https://colab.research.google.com/github/facebookresearch/mae/blob/main/demo/mae_visualize.ipynb) which
> 
> 1. first saves the predicted image and mask into numpy array
> 2. then visualize each frame in the video by re-arranging and re-normalizing and then saving it as png file
> 
> I will try to find my script and post it here. But, I would say it is a modification on top of the above python notebook file.

I'm sorry to bother you, but I want to ask if you have found your notes and could you share an example? My ability to draw 3d mask reconstruction images is limited
